{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "edgecdnx-api.fullname" . }}
  labels:
    {{- include "edgecdnx-api.labels" . | nindent 4 }}
rules:
- apiGroups: ["infrastructure.edgecdnx.com"]
  resources: ["prefixlists", "locations", "services", "projects", "zones"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["applicationsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "watch", "list"]
{{- end }}

{{- if .Values.serviceAccount.create -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "edgecdnx-api.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "edgecdnx-api.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "edgecdnx-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}