{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgecdnx-controller.fullname" . }}-webhook
  labels:
    {{- include "edgecdnx-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "edgecdnx-controller.selectorLabels" . | nindent 4 }}
{{- end }}