{{- if eq "true" .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "edgecdnx-controller.fullname" . }}-validation-webhook
  labels:
    {{- include "edgecdnx-controller.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "edgecdnx-controller.fullname" . }}
webhooks:
- name: service-validate.edgecdnx.com
  clientConfig:
    service:
      name: {{ include "edgecdnx-controller.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-infrastructure-edgecdnx-com-v1alpha1-service
  rules:
  - operations: ["CREATE", "UPDATE", "DELETE"]
    apiGroups: ["infrastructure.edgecdnx.com"]
    apiVersions: ["v1alpha1"]
    resources: ["services"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
- name: zone-validate.edgecdnx.com
  clientConfig:
    service:
      name: {{ include "edgecdnx-controller.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-infrastructure-edgecdnx-com-v1alpha1-zone
  rules:
  - operations: ["CREATE", "UPDATE", "DELETE"]
    apiGroups: ["infrastructure.edgecdnx.com"]
    apiVersions: ["v1alpha1"]
    resources: ["zones"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
{{- end }}