{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "locations-argocd-plugin.serviceAccountName" . }}
  labels:
    {{- include "locations-argocd-plugin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - locations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "locations-argocd-plugin.serviceAccountName" . }}
  labels:
    {{- include "locations-argocd-plugin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "locations-argocd-plugin.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "locations-argocd-plugin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
