apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edgecdnx-ui.fullname" . }}
  labels:
    {{- include "edgecdnx-ui.labels" . | nindent 4 }}
data:
  config.json: |
    {{- toJson .Values.config | nindent 4 }}